
#-----------------------------------------------
# https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/
#-----------------------------------------------

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/takamachi-walk-wither-album-cover.jpg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/takamachi-walk-lamento.jpg
    fit_mode = cover
}

